name: Circuit Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test_circuit:
    name: Check the Schnorr prove, verify algorithm circuit
    runs-on: ubuntu-latest
    env: 
      TEST_MODE: true
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: install dependencies
      run : npm install
      
    - name: install circom
      uses: addnab/docker-run-action@v3
      with:
        image: pleiadex/amd64-circom:2.0.5
        shell: bash
        options: -v ${{ github.workspace }}:/var/workspace
        run: |
              source "$HOME/.cargo/env"
              cd /var/workspace/resource/subcircuits
              ./compile.sh
  
    - name: build
      run : npm run buildcli
    
    - name: build QAP
      run : node . qap-all bn128 12 18 -v
    
    - name: universial setup
      run : node . setup param_12_18 rs_18 QAP_12_18 1 -v 
    
    - name: derive
      run : |
            node . derive rs_18 crsSchnorr_prove schnorr_prove QAP_12_18 -v
            node . derive rs_18 crsSchnorr_verify schnorr_verify QAP_12_18 -v
      
    - name: prove
      run : |
            node . prove crsSchnorr_prove proof1 schnorr_prove 1 1 -v
            node . prove crsSchnorr_prove proof2 schnorr_prove 2 1 -v
            node . prove crsSchnorr_verify proof schnorr_verify 1 1 -v
            
      
    - name: verify
      run : |
            node . verify proof1 crsSchnorr_prove schnorr_prove 1 -v  | tee output1
            node . verify proof2 crsSchnorr_prove schnorr_prove 2 -v  | tee output2
            node . verify proof crsSchnorr_verify schnorr_verify 1 -v | tee output3
    
    - name: check the final results
      run : |
            for f in output*; do
              if grep -q INVALID "$f"; then
                echo "The proofs are not valid"
                exit 1
              fi
            done
