name: Circuit Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  check-test-circuit:
    name: Check the Schnorr proving algorithm circuit
    runs-on: ubuntu-latest
    env: 
      TEST_MODE: true
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: install dependencies
      run : npm install
      
    - name: install circom
      uses: addnab/docker-run-action@v3
      with:
        image: pleiadex/amd64-circom:2.0.5
        shell: bash
        options: -v ${{ github.workspace }}:/var/workspace
        run: |
              source "$HOME/.cargo/env"
              resource/subcircuits/compile.sh
  
    # - name: build
    #   run : npm run buildcli
    
    - name: build QAP
      run : node cli.js qap-all bn128 12 18 -v
    
    - name: setup
      run : node cli.js setup param_12_18 rs_18 QAP_12_18 1 -v 
    
    - name: derive
      run : node cli.js derive rs_18 crsSchnorr_prove schnorr_prove QAP_12_18 -v 
      
    - name: prove
      run : node cli.js prove crsSchnorr_prove proof1 schnorr_prove 1 1 -v
      
    - name: verify
      run : |
            node cli.js verify proof1 crsSchnorr_prove schnorr_prove 1 | tee output
            echo "VALID" > expect
    
    - name: check the final result
      uses: GuillaumeFalourd/diff-action@v1
      with:
        first_file_path: output
        second_file_path: expect
        expected_result: PASSED

