name: Lint
on: [push]
jobs:
  eslint_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: eslint
      run: npx eslint src/*.js
